name: badboys
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dev_dependencies:
  json_serializable: ^6.5.0
  build_runner: ^2.3.0

dependencies:
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  get: ^4.6.5
  shared_preferences: ^2.0.11
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  responsive_sizer: ^3.3.1
  go_router: ^13.0.1
  google_sign_in: ^6.1.0
  json_annotation: ^4.7.0
  cached_network_image: ^3.2.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage : ^9.2.4
  file_picker: ^8.1.7
  image_picker: ^1.0.4
  image_cropper: ^9.0.0
  permission_handler: ^10.0.0
  flutter_lints: ^3.0.0
  flutter_local_notifications: ^9.0.0
  stomp_dart_client: ^1.0.0
  web_socket_channel: ^2.4.0
  intl: ^0.18.0

  flutter:
    sdk: flutter
  firebase_messaging: ^15.1.5


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - env/
  fonts:
    - family: Digital7
      fonts:
        - asset: assets/fonts/Digital-7.ttf
    - family: EHSMB
      fonts:
        - asset: assets/fonts/EHSMB.ttf
    - family: backToSchool
      fonts:
        - asset: assets/fonts/backToSchool.ttf